<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RpgDemo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RpgLibrary">
      <HintPath>..\RpgLibrary\bin\$(Configuration)\net10.0\RpgLibrary.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <Target Name="BuildRpgLibraryDll" BeforeTargets="ResolveReferences">
    <MSBuild
      Projects="..\RpgLibrary\RpgLibrary.csproj"
      Targets="Build"
      Properties="Configuration=$(Configuration)" />
  </Target>

</Project>
