<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RpgWinForm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RpgLibrary\RpgLibrary.csproj" />
  </ItemGroup>

</Project>
